# Redis配置块
redis:
  address:
    - 10.10.10.10:6379
    - 10.10.10.10:6379
    - 10.10.10.10:6379
    - 10.10.10.10:6379
    - 10.10.10.10:6379
    - 10.10.10.10:6379
  db: 0
  username: root
  password: password

# MySQL 配置块
mysql:
  host: 10.10.10.10
  port: 3306
  username: root
  password: password
  db: test

# Kafka集群配置块
kafka:
  username: root
  password: root
  protocol: TCP
  timeout: 10
  brokers:
    - localhost:9093
    - localhost:9092
    - localhost:9094
  topics:
    - topic-a
    - topic-b
  async: false
  allowAutoTopicCreation: true
